name: Node.js Package

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    if: github.actor != 'nektos/act'

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 21
      - run: pnpm install
      - run: pnpm run package

      - uses: actions/setup-node@v4
        with:
          registry-url: https://npm.pkg.github.com
          scope: '@natoboram'
      - run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org
          scope: '@natoboram'
      - run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

      - run: |
          gh release create ${{github.ref_name}} --generate-notes --title ${{github.ref_name}} --verify-tag
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
