name: Node.js Package

on:
  push:
    tags:
      - v*

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: 19
          registry-url: https://npm.pkg.github.com/
      - run: pnpm install
      - run: pnpm run package
      - run: pnpm publish ./package
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
